version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: simpleweather
      POSTGRES_PASSWORD: simpleweather

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379

